liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/public'
        cache_prefix: 'media/cache'

  filter_sets:
    s3_upload:
      quality: 80
      filters:
        thumbnail: { size: [1200, 800], mode: outbound }


